### ISSUE TITLE
GELF message (received from <*:*>) has invalid "timestamp"

### ISSUE THREAD

**Issue by SnazzyBootMan** [Vincit/logspout-gelf#1]
2018-01-23 14:34:54,699 WARN : org.graylog2.inputs.codecs.GelfCodec - GELF message <94044d90-004a-11e8-b29a-0242ac120004> (received from <172.18.0.1:45318>) has invalid "timestamp": 2018-01-23T14:34:54.528892092Z  (type: STRING)

I am using "logspout-gelf" to send docker output to Graylog 2.4.0 and the output is being logged but this message is also being indexed by Graylog. Killing the "logstash-gelf" docker (obviously) stops this. Restarting "logstash-gelf" indexes a few of the messages then it stops until the next event is logged in any other docker container.

example container run:
    `docker run -d --name num_gen debian:jessie bash -c 'for i in {0..2000}; do echo $i; done'`

**Comment by SnazzyBootMan** [comment]
So this is not an issue with logspout or the gelf adaptor. I had been running a Graylog cluster in docker containers and if you do not add the container environment variable "LOGSPOUT=ignore" to that cluster you will get some odd results.

**Comment by danvaida** [comment]
@SnazzyBootMan isn't this actually related to this https://github.com/mp911de/logstash-gelf/issues/125 ?

**Comment by SnazzyBootMan** [comment]
@danvaida - could be, I haven't actually looked I gave up on this some time ago and went with dockers "fluentd" driver.
